# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('tmp_max', models.IntegerField(null=True)),
                ('tmp_min', models.IntegerField(null=True)),
                ('cond_txt_d', models.CharField(max_length=20, null=True)),
                ('cond_txt_n', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RF',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('rainfall', models.FloatField(null=True)),
                ('level', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
