# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-12 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RF',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('year', models.IntegerField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('rainfall', models.FloatField(null=True)),
                ('level', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
