# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RF',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
                ('level', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
