# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFAnhui',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFBeijing',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFGansu',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFHebei',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFHeilongjiang',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFHenan',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFJiangsu',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFJilin',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFLiaoning',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFNeimenggu',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFNingxia',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFQinghai',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFShaanxi',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFShandong',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFShanxi',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFTianjin',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RFXinjiang',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
