# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drought', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='anhui',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='beijing',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gansu',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hebei',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='heilongjiang',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='henan',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jiangsu',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jilin',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='liaoning',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='neimenggu',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ningxia',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='qinghai',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shaanxi',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shandong',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='shanxi',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tianjin',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='xinjiang',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=20, null=True)),
                ('stationIndex', models.IntegerField(null=True)),
                ('Year', models.IntegerField(null=True)),
                ('Area', models.FloatField(null=True)),
                ('Precipitation', models.IntegerField(null=True)),
                ('totalPre', models.FloatField(null=True)),
                ('Comparing', models.FloatField(null=True)),
            ],
        ),
    ]
