# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drought', '0002_anhui_beijing_gansu_hebei_heilongjiang_henan_jiangsu_jilin_liaoning_neimenggu_ningxia_qinghai_shaanx'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFAnhui',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFBeijing',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFGansu',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFHebei',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFHeilongjiang',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFHenan',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFJiangsu',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFJilin',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFLiaoning',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFNeimenggu',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFNingxia',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFQinghai',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFShaanxi',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFShandong',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFShanxi',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFTianjin',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.CreateModel(
            name='RFXinjiang',
            fields=[
                ('rf_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='drought.RF')),
            ],
            bases=('drought.rf',),
        ),
        migrations.RenameModel(
            old_name='ningxia',
            new_name='RF',
        ),
        migrations.DeleteModel(
            name='anhui',
        ),
        migrations.DeleteModel(
            name='beijing',
        ),
        migrations.DeleteModel(
            name='gansu',
        ),
        migrations.DeleteModel(
            name='hebei',
        ),
        migrations.DeleteModel(
            name='heilongjiang',
        ),
        migrations.DeleteModel(
            name='henan',
        ),
        migrations.DeleteModel(
            name='jiangsu',
        ),
        migrations.DeleteModel(
            name='jilin',
        ),
        migrations.DeleteModel(
            name='liaoning',
        ),
        migrations.DeleteModel(
            name='neimenggu',
        ),
        migrations.DeleteModel(
            name='qinghai',
        ),
        migrations.DeleteModel(
            name='shaanxi',
        ),
        migrations.DeleteModel(
            name='shandong',
        ),
        migrations.DeleteModel(
            name='shanxi',
        ),
        migrations.DeleteModel(
            name='tianjin',
        ),
        migrations.DeleteModel(
            name='xinjiang',
        ),
    ]
